name: Build and Push Multiple Images to Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: 'batatta'
          password: ${{ secrets.DOCKER_TOKEN }}

      # ==========================
      # Build & Push da imagem GO
      # ==========================
      - name: Build and Push Go Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend      # ðŸ‘ˆ pasta onde estÃ¡ o Dockerfile do Go
          file: ./backend/Dockerfile
          push: true
          tags: |
            batatta/torre-do-mago-backend:latest
            batatta/torre-do-mago-backend:${{ github.sha }}

      # ==========================
      # Build & Push da imagem PYTHON
      # ==========================
      - name: Build and Push Python Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./ai-service  # ðŸ‘ˆ pasta onde estÃ¡ o Dockerfile do Python
          file: ./ai-service/Dockerfile
          push: true
          tags: |
            batatta/torre-do-mago-python:latest
            batatta/torre-do-mago-python:${{ github.sha }}
